version: 2.1

# orbs:
#   node: circleci/node@4.7

# jobs:
#   build-and-test:
#     executor:
#       name: node/default
#     steps:
#       - checkout
#       - node/install-packages:
#           pkg-manager: npm
#       - run: npm install
#           # command: npm install
#           # name: install
#       - run: npm test        
#           # command: npm test
#           # name: test
# workflows:
#   build-and-test:
#     jobs: 
#       - build-and-test

jobs:
  build: 
    docker:
       - image: circleci/node:16.14.1
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CURRENT_BRANCH}
      - restore_cache:
          keys:
            - app-{{ checksum "package.json" }}
            - app-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: app-({ checksum "package.json" })